### ISSUE TITLE
Inclusive naming

### ISSUE THREAD

**Issue by jamesgeddes** [botlabs-gg/yagpdb#1185] opened 2022-04-22 09:52 UTC
May I request that YAGPDB migrates to using inclusive naming, please? 

https://inclusivenaming.org/word-lists/tier-1/

This includes, but is not limited to,
- default branch name
- variable names
- user interface

Thanks

**Comment by l-zeuch** [comment] 2022-04-22 09:54
Don't spam new issues if old ones were closed with a clear statement.

**Comment by ashishjh-bst** [comment] 2022-04-22 09:54
Duplicate of https://github.com/botlabs-gg/yagpdb/issues/1184

**Closed** 2022-04-22 09:53 UTC

**Comment by ashishjh-bst** [comment] 2022-04-22 09:55
Duplicate of the following issue: https://github.com/botlabs-gg/yagpdb/issues/1183
